sudo: required
dist: trusty

cache: packages
addons:
  apt:
    sources:
      - sourceline: "ppa:team-gcc-arm-embedded/ppa"
    packages:
      - lib32z1
      - lib32ncurses5
      - lib32bz2-1.0
      - gcc-arm-embedded

language: cpp
compiler: gcc

script:
  - make
