dist: trusty

cache: packages

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: "ppa:team-gcc-arm-embedded/ppa"
            - ubuntu-toolchain-r-test
          packages:
            - lib32z1
            - lib32ncurses5
            - lib32bz2-1.0
            - gcc-arm-embedded
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

language: cpp
compiler: gcc

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - make
  - mkdir cmake-build-debug
  - cd cmake-build-debug
  - cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" ..
  - cmake --build . --target OkapiLibV5 -- -j 2
  - ./OkapiLibV5
