baseurl = "https://okapilib.github.io/OkapiLib/"
languageCode = "en-us"
title = "Okapi Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
googleAnalytics = "UA-108357936-1"
publishDir = "../docs"

[params]
	# General information
	author = "OkapiLib"
	description = "A PROS library for fast C++ development."
	copyright = ""

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/OkapiLib/OkapiLib"

	version = "0.2.4"
	logo = "images/okapi.jpg"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = ["css/imageAlign.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "OkapiLib"
	email   = ""


[[menu.main]]
	name   = "Home"
	url    = "home/"
	weight = 10

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 20

[[menu.main]]
	name   = "Tutorials"
	url    = "tutorials/"
	weight = 30

[[menu.main]]
	name   = "API"
	url    = "api/"
	weight = 40

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 50


[blackfriday]
	smartypants    = true
	fractions      = true
	smartDashes    = true
	plainIDAnchors = true
