baseURL = "https://okapilib.github.io/OkapiLib/"
languageCode = "en-us"
title = "OkapiLib Docs"
theme = "docuapi"
publishDir = "../docs"

pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsOptions = ""
pygmentsStyle = "monokai"
pygmentsUseClasses = true

defaultContentLanguage = "en"

[params]
search = true
